/**
 * Generates .env.example and the environment reference table in
 * docs/CONFIGURATION.md from the component manifests.
 *
 * Documentation that is written by hand drifts from the code the first time
 * someone adds a variable. Generating it means the manifest is the single source
 * of truth, and `npm run gen:env -- --check` fails CI when the two disagree.
 */
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { loadRegistry } from '../src/server/lib/registry.js';
import { CORE_ENV } from '../src/server/lib/env.js';

const ENV_PATH = path.resolve(process.cwd(), '.env.example');
const DOCS_PATH = path.resolve(process.cwd(), 'docs', 'CONFIGURATION.md');
const START = '<!-- BEGIN GENERATED ENV TABLE -->';
const END = '<!-- END GENERATED ENV TABLE -->';

interface Row {
  name: string;
  component: string;
  required: boolean;
  description: string;
}

async function collect(): Promise<Row[]> {
  const { components } = await loadRegistry();
  const rows: Row[] = [];

  for (const [name, description] of Object.entries(CORE_ENV)) {
    rows.push({ name, component: 'core', required: false, description });
  }

  for (const { definition } of components) {
    const describe = definition.env?.describe ?? {};
    for (const req of definition.env?.required ?? []) {
      rows.push({ name: req, component: definition.id, required: true, description: describe[req] ?? '' });
    }
    for (const opt of definition.env?.optional ?? []) {
      rows.push({ name: opt, component: definition.id, required: false, description: describe[opt] ?? '' });
    }
  }

  return rows;
}

function renderEnvExample(rows: Row[]): string {
  const lines = [
    '# Generated by `npm run gen:env` from the component manifests. Do not edit by hand.',
    '#',
    '# Copy to .env and fill in. This file holds every secret and every LAN address:',
    '# it is gitignored, it is never baked into the published image, and none of it',
    '# is ever sent to the browser.',
    '',
    '# Timezone for the container itself; the dashboard uses config/public.json.',
    'TZ=Europe/Oslo',
    '',
  ];

  const byComponent = new Map<string, Row[]>();
  for (const row of rows) {
    if (!byComponent.has(row.component)) byComponent.set(row.component, []);
    byComponent.get(row.component)!.push(row);
  }

  for (const [component, componentRows] of byComponent) {
    lines.push(`# --- ${component} ${'-'.repeat(Math.max(0, 68 - component.length))}`);
    for (const row of componentRows) {
      if (row.description) {
        for (const chunk of wrap(row.description, 76)) lines.push(`# ${chunk}`);
      }
      lines.push(row.required ? `${row.name}=` : `# ${row.name}=`);
      lines.push('');
    }
  }

  return lines.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';
}

function renderDocsTable(rows: Row[]): string {
  const lines = [
    '| Variable | Component | Required | Description |',
    '| --- | --- | --- | --- |',
  ];
  for (const row of rows) {
    lines.push(
      `| \`${row.name}\` | ${row.component} | ${row.required ? 'yes' : 'no'} | ${row.description.replace(/\|/g, '\\|')} |`,
    );
  }
  return lines.join('\n');
}

function wrap(text: string, width: number): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let line = '';
  for (const word of words) {
    if (line.length + word.length + 1 > width && line) {
      lines.push(line);
      line = word;
    } else {
      line = line ? `${line} ${word}` : word;
    }
  }
  if (line) lines.push(line);
  return lines;
}

const rows = await collect();
const envExample = renderEnvExample(rows);
const table = renderDocsTable(rows);

let docs = await readFile(DOCS_PATH, 'utf8').catch(() => '');
if (docs.includes(START) && docs.includes(END)) {
  docs = docs.replace(
    new RegExp(`${START}[\\s\\S]*?${END}`),
    `${START}\n\n${table}\n\n${END}`,
  );
}

const check = process.argv.includes('--check');
if (check) {
  const currentEnv = await readFile(ENV_PATH, 'utf8').catch(() => '');
  const currentDocs = await readFile(DOCS_PATH, 'utf8').catch(() => '');
  if (currentEnv !== envExample || (docs && currentDocs !== docs)) {
    console.error('.env.example or docs/CONFIGURATION.md is out of date. Run: npm run gen:env');
    process.exit(1);
  }
  console.log('generated files are up to date');
} else {
  await writeFile(ENV_PATH, envExample);
  if (docs) await writeFile(DOCS_PATH, docs);
  console.log(`wrote .env.example (${rows.length} variables)`);
}
